name: dispatch-test_json
on:
  workflow_dispatch:
    inputs:
      json:
        type: string
        description: 'Location of the testplan'
        required: false
        default: https://raw.githubusercontent.com/joernott/action-test/main/.testplans/basic.json
      yaml:
        type: string
        description: 'Location of the testplan'
        required: false
        default: https://raw.githubusercontent.com/joernott/action-test/main/.testplans/basic.yml
      runs_on:
        type: string
        description: 'Runner for this workflow'
        required: false
        default: '"ubuntu-latest"'

jobs:
  test_jsontovariables:
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - name: "Download testplan"
        run: |
          #curl -sSjkLo .testplan.yml "${{ inputs.yaml }}"
          curl -sSjkLo .testplan.json "${{ inputs.json }}"
      - name: 'Load variables'
        uses: laingcc/json-to-variables@release
        with:
          filename: .testplan.json
          prefix: 'x'
      - name: 'Dump variables'
        run: |
          cat <<EOF
            x_workflow_matrix_php: $x_workflow_matrix_php
            x_workflow_matrix_mysql: $x_workflow_matrix_mysql
            x_workflow_runs_on: $x_workflow_runs_on

            x_test_string: $x_test_string
            x_test_wahr: $x_test_wahr
            x_test_falsch: $x_test_falsch
            x_test_number: $x_test_number
          EOF
  test_yamloutputs:
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - name: "Download testplan"
        run: |
          cat >.testplan.yml <<EOF
          github:
            action: &github_action '${{ github.action }}'
            action_path: &github_action_path '${{ github.action_path }}'
            action_ref: &github_action_ref '${{ github.action_ref }}'
            action_repository: &github_action_repository '${{ github.action_repository }}'
            action_status: &github_action_status '${{ github.action_status }}'
            actor: &github_actor '${{ github.actor }}'
            actor_id: &github_actor_id '${{ github.actor_id }}'
            api_url: &github_api_url '${{ github.api_url }}'
            base_ref: &github_base_ref '${{ github.base_ref }}'
            env: &github_env '${{ github.env }}'
            event: &github_event '${{ github.event }}'
            event_name: &github_event_name '${{ github.event_name }}'
            event_path: &github_event_path '${{ github.event_path }}'
            graphql_url: &github_graphql_url '${{ github.graphql_url }}'
            head_ref: &github_head_ref '${{ github.head_ref }}'
            job: &github_job '${{ github.job }}'
            job_workflow_sha: &github_job_workflow_sha '${{ github.job_workflow_sha }}'
            path: &github_path '${{ github.path }}'
            ref: &github_ref '${{ github.ref }}'
            ref_name: &github_ref_name '${{ github.ref_name }}'
            ref_protected: &github_ref_protected '${{ github.ref_protected }}'
            ref_type: &github_ref_type '${{ github.ref_type }}'
            repository: &github_repository '${{ github.repository }}'
            repository_id: &github_repository_id '${{ github.repository_id }}'
            repository_owner: &github_repository_owner '${{ github.repository_owner }}'
            repository_owner_id: &github_repository_owner_id '${{ github.repository_owner_id }}'
            repositoryUrl: &github_repositoryUrl '${{ github.repositoryUrl }}'
            retention_days: &github_retention_days '${{ github.retention_days }}'
            run_id: &github_run_id '${{ github.run_id }}'
            run_number: &github_run_number '${{ github.run_number }}'
            run_attempt: &github_run_attempt '${{ github.run_attempt }}'
            secret_source: &github_secret_source '${{ github.secret_source }}'
            server_url: &github_server_url '${{ github.server_url }}'
            sha: &github_sha '${{ github.sha }}'
            token: &github_token '${{ github.token }}'
            triggering_actor: &github_triggering_actor '${{ github.triggering_actor }}'
            workflow: &github_workflow '${{ github.workflow }}'
            workflow_ref: &github_workflow_ref '${{ github.workflow_ref }}'
            workflow_sha: &github_workflow_sha '${{ github.workflow_sha }}'
            workspace: &github_workspace '${{ github.workspace }}'
          EOF
          curl -sSjkL "${{ inputs.yaml }}" >>.testplan.yml
          cat .testplan.yml

      - name: 'Load variables'
        uses: actions-tools/yaml-outputs@v2
        id: yaml
        with:
          file-path: .testplan.yml
          separator: '_'
      - name: 'Dump variables'
        run: |
          cat <<EOF
            workflow_matrix_php: $workflow_matrix_php
            workflow_matrix_mysql: $workflow_matrix_mysql
            workflow_runs_on: $workflow_runs_on

            test_string: $test_string
            test_wahr: $test_wahr
            test_falsch: $test_falsch
            test_number: $test_number
          EOF
