name: dispatch-test_json
on:
  workflow_dispatch:
    inputs:
      json:
        type: string
        description: 'Location of the testplan'
        required: false
        default: https://raw.githubusercontent.com/joernott/action-test/main/.testplans/basic.json
      yaml:
        type: string
        description: 'Location of the testplan'
        required: false
        default: https://raw.githubusercontent.com/joernott/action-test/main/.testplans/basic.yml
      runs_on:
        type: string
        description: 'Runner for this workflow'
        required: false
        default: '"ubuntu-latest"'

jobs:
  test_varfilestoenv:
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - name: "Download testplan"
        run: |
          curl -sSjkLo .testplan.yml "${{ inputs.yaml }}"
          curl -sSjkLo .testplan.json "${{ inputs.json }}"

      - name: 'Load yaml variables'
        uses: zlatko-ms/varfiletoenv@v3
        with:
          paths: .testplan.yml
      - name: 'Dump variables'
        run: |
          cat <<EOF
            workflow_matrix_php: $workflow_matrix_php
            workflow_matrix_mysql: $workflow_matrix_mysql
            workflow_runs_on: $workflow_runs_on

            test_string: $test_string
            test_wahr: $test_wahr
            test_falsch: $test_falsch
            test_number: $test_number
          EOF
      - name: 'Load json variables'
        uses: zlatko-ms/varfiletoenv@v3
        with:
          paths: .testplan.yml
      - name: 'Dump variables'
        run: |
          cat <<EOF
            workflow_matrix_php: $workflow_matrix_php
            workflow_matrix_mysql: $workflow_matrix_mysql
            workflow_runs_on: $workflow_runs_on

            test_string: $test_string
            test_wahr: $test_wahr
            test_falsch: $test_falsch
            test_number: $test_number
          EOF

  test_jsontovariables:
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - name: "Download testplan"
        run: |
          #curl -sSjkLo .testplan.yml "${{ inputs.yaml }}"
          curl -sSjkLo .testplan.json "${{ inputs.json }}"
      - name: 'Load variables'
        uses: laingcc/json-to-variables@release
        with:
          filename: .testplan.json
          prefix: 'x'
      - name: 'Dump variables'
        run: |
          cat <<EOF
            x_workflow_matrix_php: $x_workflow_matrix_php
            x_workflow_matrix_mysql: $x_workflow_matrix_mysql
            x_workflow_runs_on: $x_workflow_runs_on

            x_test_string: $x_test_string
            x_test_wahr: $x_test_wahr
            x_test_falsch: $x_test_falsch
            x_test_number: $x_test_number
          EOF
  test_yamloutputs:
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - name: "Download testplan"
        run: |
          curl -sSjkLo .testplan.yml "${{ inputs.yaml }}"
          #curl -sSjkLo .testplan.json "${{ inputs.json }}"
      - name: 'Load variables'
        uses: actions-tools/yaml-outputs@v2
        id: yaml
        with:
          file-path: .testplan.yml
      - name: 'Dump variables'
        run: |
          cat <<EOF
            workflow_matrix_php: $workflow_matrix_php
            workflow_matrix_mysql: $workflow_matrix_mysql
            workflow_runs_on: $workflow_runs_on

            test_string: $test_string
            test_wahr: $test_wahr
            test_falsch: $test_falsch
            test_number: $test_number
          EOF
