name: docker_settings
# Tests for the docker proxy stuff
on:
  workflow_dispatch:
    inputs:
      runs_on:
          type: string
          description: 'Runner for this workflow'
          required: false
          default: '["self-hosted", "x64"]'
#     secrets:
#       DOCKER_HUB_USER:
#         description: 'user for the docker login'
#         required: false
#       DOCKER_HUB_TOKEN:
#         description: 'Token for the docker login'
#         required: false
jobs:
  init:
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    steps:
      - name: 'Initialize'
        run: |
          DOCKER_LOGIN="false"
          [ -n "${{ secrets.DOCKER_HUB_TOKEN }}" ] && DOCKER_LOGIN="true"
          echo "DOCKER_LOGIN=$DOCKER_LOGIN" | tee $GITHUB_ENV

      - name: 'Get docker config info'
        run: |
          sudo find /etc |sort >etc.txt
          docker info >docker_info.txt
          ps auxw >ps.txt
          mount >mount.txt

      - name: 'Check, if we can reach harbor'
        if: always()
        run: |
          nslookup harbor.testlab.ott-consult.de

#      - name: 'Configure docker'
#        if:
#        run: |
#          sudo mkdir /etc/docker && \
#          sudo cat >/etc/docker/daemon.json <<EOF
#          {
#            "registry-mirrors": ["http://harbor-transparent-proxy-nginx.harbor.svc.cluster.local:30005"],
#            "insecure-registries": ["http://harbor-transparent-proxy-nginx.harbor.svc.cluster.local:30005"]
#          }
#          EOF

      - name: Upload Log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            *.txt
            /entrypoint.sh
          if-no-files-found: error
          retention-days: 1
